CREATE TYPE ADRECA AS OBJECT (
carrer VARCHAR(50),
ciutat VARCHAR(10),
codi_postal NUMBER
);

CREATE TYPE TELEFON AS OBJECT (
tipus VRACHAR(20),
numero VARCHAR(15)
);

CREATE TYPE VEC_TELEFONS AS VARRAY(2) OF TELEFON;

CREATE TYPE PROVEIDOR AS OBJECT (
codi NUMBER,
nom VARCHAR2(50),
adreca ADRECA,
vec_telefons VEC_TELEFONS,
correu_electronic VARCHAR(50),
);

CREATE TYPE MATERIAL AS OBJECT (
codi NUMBER,
nom VARCHAR(50),
descripcio VARCHAR(200),
cost_unitari NUMBER(5,2)
);

CREATE TYPE LINIA_COMPRA AS OBJECT (
codi NUMBER,
ref_material REF material,
quantitat NUMBER,
descompte NUMBER
);

CREATE TYPE linies AS TABLE OF LINIA_COMPRA;

CREATE TYPE COMPRA AS OBJECT (
codi NUMBER, 
data_compra NUMBER,
ref_proveidor REF PROVEIDOR,
taula_linies linies
);

CREATE TABLE Materiales OF MATERIAL(PRIMARY KEY(codi));
CREATE TABLE Proveidores OF PROVEIDOR(PRIMARY KEY(codi));
CREATE TABLE Compras OF COMPRA(PRIMARY KEY(codi));
